= eudaimon.io

I currently have the problem, that to calculate the center force in my embedder,
I use a DrawingRect as the center, but that doesn't really make any sense. A
Point would make much more sense, but using a Point is not possible since to
calculate forces a do need the width and height of the nodes.

Another reason, why I want to change the center to something difference then a
DrawingRect is, because I will introduce a new argument in the contructor. Then
the center would also need a text which really doesn't make any sense at all.

I need better way to calculate the force between nodes. Then being said, maybe I
should start be renaming DrawingRect to DrawingVertex, as this is what it is.

== Note

- The order of `set.label` und `Canvas.addDrawing()` matters, since
`getComputedTextLength()` only works if the text is rendered.

== wrapText()

The wrapText method calculates uses the `getComputedTextLength()` function to
get the length of the rendered text. In iterative approach, each word is
appended until a defined `maxLength` is reached. Then a new line is created and
so on.

[code, typescript]
----
words.forEach((word) => {
    line.push(word);
    tspan.textContent = line.join(' ');
    if (tspan.getComputedTextLength() > maxLength) {
        const poppedWord = line.pop();
        tspan.textContent = line.join(' ');
        line = [poppedWord];
        tspan = document.createElementNS(namespace, 'tspan');
        tspan.textContent = line.join(' ');
    }
});
----